# global search settings
use_icons:    true
ignore_case:  true
search_regex: false

# window settings
window:
  title: "Rmenu - Application Launcher"
  size:
    width:  800
    height: 400
  position:
    x: 300
    y: 500
  focus:       true
  decorate:    false
  transparent: false
  always_top:  true

# configured plugin settings
plugins:
  run:
    exec:  ["~/.config/rmenu/plugins/rmenu-run"]
    cache: 300
  drun:
    exec:  ["~/.config/rmenu/plugins/rmenu-desktop"]
    cache: onlogin
    options:
      css: ~/.config/rmenu/themes/launchpad.css
      hover_select: true
      single_click: true
      context_menu: true
      page_size: 500
      transparent: true
      window_width: 1200
      window_height: 800
      key_move_prev: ["Arrow-Left"]
      key_move_next: ["Arrow-Right"]
      key_jump_prev: ["Arrow-Up"]
      key_jump_next: ["Arrow-Down"]
  emoji:
    exec:  ["~/.config/rmenu/plugins/rmenu-emoji"]
    cache: false
    placeholder: "Search an Emoji"
    options:
      css: ~/.config/rmenu/plugins/css/emojis.css
      hover_select: true
      single_click: true
      context_menu: true
      key_move_prev: ["Arrow-Left"]
      key_move_next: ["Arrow-Right"]
      key_jump_prev: ["Arrow-Up"]
      key_jump_next: ["Arrow-Down"]
  network:
    exec:  ["~/.config/rmenu/plugins/rmenu-network"]
    cache: false
    placeholder: "Connect to the Specified Wi-Fi"
  window:
    exec:  ["~/.config/rmenu/plugins/rmenu-window"]
    cache: false
    placeholder: "Jump to the Specified Window"
  audio:
    exec:  ["~/.config/rmenu/plugins/pactl-audio.sh"]
    cache: false
    placeholder: "Select an Audio Sink"
  powermenu:
    exec: ["~/.config/rmenu/plugins/powermenu.sh"]
    cache: false
    options:
      hover_select: true
      single_click: true

# custom keybindings
keybinds:
  exec:       ["Enter"]
  exit:       ["Escape"]
  move_next:  ["Arrow-Down", "Tab"]
  move_prev:  ["Arrow-Up", "Shift+Tab"]
  jump_next:  ["Page-Down"]
  jump_prev:  ["Page-Up"]
  open_menu:  ["Arrow-Right"]
  close_menu: ["Arrow-Left"]
