[workspace]
resolver = "2"
members = [
  "rmenu",
  "rmenu-plugin",
  "plugins/desktop",
  "plugins/emoji",
  "plugins/files",
  "plugins/network",
  "plugins/run",
  "plugins/window", "plugins/files",
]
